version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: raginraju
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  ecommerce-store:
    build: ./ecommerce-store
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: raginraju
    depends_on:
      - mysql

  ecommerce-frontend:
    build: ./ecommerce-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - ecommerce-store

volumes:
  mysql_data:
